// <auto-generated />
using System;
using GameStore.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameStore.DAL.Migrations
{
    [DbContext(typeof(GamestoredbContext))]
    partial class GamestoredbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("GameStore.Domain.Models.Activation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique();

                    b.ToTable("activation");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique()
                        .HasDatabaseName("name1");

                    b.ToTable("developer");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("avatar_path")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("int(11)")
                        .HasColumnName("developer_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("price");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int(11)")
                        .HasColumnName("publisher_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime>("ReleaseOn")
                        .HasColumnType("date")
                        .HasColumnName("release_on");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("video_url")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DeveloperId" }, "developer_id");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique()
                        .HasDatabaseName("name2");

                    b.HasIndex(new[] { "PublisherId" }, "publisher_id");

                    b.ToTable("game");
                });

            modelBuilder.Entity("GameStore.Domain.Models.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("int(11)")
                        .HasColumnName("genre_id");

                    b.HasKey("GameId", "GenreId")
                        .HasName("PRIMARY");

                    b.HasIndex("GenreId");

                    b.ToTable("game_genre");
                });

            modelBuilder.Entity("GameStore.Domain.Models.GameOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("order_id");

                    b.Property<int>("GameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game_id");

                    b.HasKey("OrderId", "GameId")
                        .HasName("PRIMARY");

                    b.HasIndex("GameId");

                    b.ToTable("game_order");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique()
                        .HasDatabaseName("name3");

                    b.ToTable("genre");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Key", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int?>("ActivationId")
                        .HasColumnType("int(11)")
                        .HasColumnName("activation_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("GameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_used");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ActivationId" }, "activation_id");

                    b.HasIndex(new[] { "GameId" }, "game_id");

                    b.HasIndex(new[] { "Value" }, "value")
                        .IsUnique();

                    b.ToTable("key");
                });

            modelBuilder.Entity("GameStore.Domain.Models.MinimumSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("GameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game_id");

                    b.Property<string>("Graphics")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("graphics");

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("memory");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("os");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int(11)")
                        .HasColumnName("platform_id");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("processor");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("storage");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GameId" }, "game_id")
                        .HasDatabaseName("game_id1");

                    b.HasIndex(new[] { "PlatformId", "GameId" }, "platform_id_game_id")
                        .IsUnique();

                    b.ToTable("minimum_specification");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("PayOn")
                        .HasColumnType("date")
                        .HasColumnName("pay_on");

                    b.Property<int?>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("order");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique()
                        .HasDatabaseName("name4");

                    b.ToTable("platform");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique()
                        .HasDatabaseName("name5");

                    b.ToTable("publisher");
                });

            modelBuilder.Entity("GameStore.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("balance");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mail");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Game", b =>
                {
                    b.HasOne("GameStore.Domain.Models.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .HasConstraintName("FK_game_developer_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameStore.Domain.Models.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .HasConstraintName("FK_game_publisher_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("GameStore.Domain.Models.GameGenre", b =>
                {
                    b.HasOne("GameStore.Domain.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_game_genre_game_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Domain.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("FK_game_genre_genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameStore.Domain.Models.GameOrder", b =>
                {
                    b.HasOne("GameStore.Domain.Models.Game", "Game")
                        .WithMany("GameOrders")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_game_order_game_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Domain.Models.Order", "Order")
                        .WithMany("GameOrders")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_game_order_order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Key", b =>
                {
                    b.HasOne("GameStore.Domain.Models.Activation", "Activation")
                        .WithMany("Keys")
                        .HasForeignKey("ActivationId")
                        .HasConstraintName("FK_key_activation_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameStore.Domain.Models.Game", "Game")
                        .WithMany("Keys")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_key_game_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activation");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameStore.Domain.Models.MinimumSpecification", b =>
                {
                    b.HasOne("GameStore.Domain.Models.Game", "Game")
                        .WithMany("MinimumSpecifications")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_minimum_specification_game_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Domain.Models.Platform", "Platform")
                        .WithMany("MinimumSpecifications")
                        .HasForeignKey("PlatformId")
                        .HasConstraintName("FK_minimum_specification_platform_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Order", b =>
                {
                    b.HasOne("GameStore.Domain.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_order_user_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Activation", b =>
                {
                    b.Navigation("Keys");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("GameOrders");

                    b.Navigation("Keys");

                    b.Navigation("MinimumSpecifications");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Order", b =>
                {
                    b.Navigation("GameOrders");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Platform", b =>
                {
                    b.Navigation("MinimumSpecifications");
                });

            modelBuilder.Entity("GameStore.Domain.Models.Publisher", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameStore.Domain.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
